import { StyleSheet } from 'react-native';
import { BorderRadius, Colors, Spacing, Typography } from '../../constants/theme';

// Estilos usados en los componentes de paso (PasoTriage, PasoDiagnostico, etc.)
export const s = StyleSheet.create({
  step:         { padding: Spacing.lg, paddingTop: Spacing.xl, gap: Spacing.lg },
  iconBox:      { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  title:        { ...Typography.h4, color: Colors.dark },
  sub:          { ...Typography.body, color: Colors.darkGray, lineHeight: 26 },
  bold:         { fontWeight: '700', color: Colors.dark },
  hint:         { ...Typography.caption, color: Colors.gray, textAlign: 'center' },
  optBtn:       { flexDirection: 'row', alignItems: 'center', padding: Spacing.lg, borderRadius: BorderRadius.large, borderWidth: 2, gap: Spacing.md, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 2, elevation: 2 },
  optLabel:     { fontSize: 16, fontWeight: '700' },
  optDesc:      { ...Typography.caption, color: Colors.gray, marginTop: 2 },
  diagBtn:      { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, padding: Spacing.lg, borderRadius: BorderRadius.large, borderWidth: 2 },
  diagLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  diagLabel:    { fontSize: 14, fontWeight: '700' },
  diagTag:      { paddingVertical: 2, paddingHorizontal: 7, borderRadius: 5 },
  diagTagTxt:   { fontSize: 10, fontWeight: '700' },
  diagDesc:     { ...Typography.bodyXSmall, color: Colors.gray },
  radio:        { width: 20, height: 20, borderRadius: 10, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkRow:     { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, padding: Spacing.md, borderRadius: BorderRadius.medium, backgroundColor: Colors.surface, borderWidth: 1.5, borderColor: Colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 2, elevation: 1 },
  checkRowOn:   { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  chk:          { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: Colors.gray, alignItems: 'center', justifyContent: 'center' },
  chkOn:        { backgroundColor: Colors.primary, borderColor: Colors.primary },
  checkLabel:   { ...Typography.bodySmall, color: Colors.darkGray, flex: 1 },
  checkLabelOn: { color: Colors.primary, fontWeight: '600' },
  badge:        { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, padding: Spacing.lg, borderRadius: BorderRadius.large, borderWidth: 2 },
  badgeLabel:   { fontSize: 17, fontWeight: '800' },
  badgeSub:     { ...Typography.caption, color: Colors.gray, marginTop: 2 },
  subSection:   { ...Typography.bodySmall, fontWeight: '700', color: '#6D28D9', marginBottom: 4 },
  card:         { backgroundColor: Colors.surface, borderRadius: BorderRadius.large, padding: Spacing.lg, gap: Spacing.md, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  micRef:       { ...Typography.caption, color: Colors.gray, marginBottom: 2 },
  micBlock:     { borderLeftWidth: 4, paddingLeft: Spacing.md, marginBottom: Spacing.sm, gap: Spacing.xs },
  micTituloRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  micTitulo:    { ...Typography.label },
  micTxt:       { ...Typography.bodyXSmall, color: Colors.darkGray, lineHeight: 18 },
  segRow:       { flexDirection: 'row', gap: Spacing.md, alignItems: 'flex-start', borderLeftWidth: 3, paddingLeft: Spacing.md, paddingVertical: Spacing.xs },
  segTxt:       { ...Typography.bodySmall, color: Colors.dark, flex: 1, lineHeight: 18 },
  btnReset:     { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, backgroundColor: Colors.primary, paddingVertical: Spacing.md, paddingHorizontal: Spacing.xxxl, borderRadius: BorderRadius.large, marginTop: Spacing.md },
});